### ISSUE TITLE
New integration with Precision Gaze Mouse

### ISSUE THREAD

**Issue by nash8350** [cmauri/eviacam#13]
Hi I am the creator of Precision Gaze Mouse and I thought you'd like to hear that I've integrated support for eViacam. One of your users made the suggestion to use eViacam and I really like it!

Precision Gaze Mouse allows people to use eye trackers like Tobii EyeX to quickly jump the mouse across the screen just by looking with their eyes. I paired it with eViacam by turning the X and Y speed down so that I can have small precision movements when I rotate my head. It can also reduce fatigue because you don't need to rotate your head so much. It's open source and you can check it out here http://precisiongazemouse.com/

If you think this is something other users might find useful, it would be great to have a link in your Related Projects section :smiley: I also added a link to your site from the setup docs.

**Comment by cmauri** [comment]
Hi,
Apologies for the delay. I'm very happy to hear that you integrated support for eViacam. I found very interesting the Precision Game Mouse approach to combine both eye tracking with face tracking. Congratulations! Of course, I will share this information with my colleagues and users and I'll add a link back to your project :smile: 

BTW, did you try your software with webcam based eye tracking?

Thank you!

**Comment by nash8350** [comment]
@cmauri hey thanks for adding a link to your homepage! I just updated the URL and now the link is broken on your site here https://eviacam.crea-si.com/. Can you update the link to https://precisiongazemouse.org/? 

Also, yes I just gave it a shot with the webcam eye tracker called gazepointer but I found the accuracy lower than EyeX. Do you have any other webcam eye tracker to recommend?

**Comment by cmauri** [comment]
Hi @nash8350 ! I've just updated the links.
Here I have a Tobii Eye Tracker 4C and works pretty well.

**Comment by nash8350** [comment]
@cmauri I think there's just a small typo. Your link says "Precision Game Mouse" but it should be "Precision Gaze Mouse"

**Comment by cmauri** [comment]
@nash8350, typo fixed
