### ISSUE TITLE
Please support OpenCV 3

### ISSUE THREAD

**Issue by iwamatsu** [cmauri/eviacam#2]
Hi, 

Current eviacam can not build with opencv 3.
Becuse eviacam is using cvCalcOpticalFlowHS, but this has been removed from opencv 3. 
We need to use cv::calcOpticalFlowFarneback instead of cvCalcOpticalFlowHS.

Best regards,
  Nobuhiro

**Comment by cmauri** [comment]
Hi Nobuhiro,

The code using cvCalcOpticalFlowHS was already deprecated in eViacam, so I removed it completely. I hope now compiles fine with opencv 3 (it works with opencv 2). Updated commits in devel branch.

Best regards,
Cesar

**Comment by iwamatsu** [comment]
Hi!

> The code using cvCalcOpticalFlowHS was already deprecated in eViacam, so I removed it completely. I hope now compiles fine with opencv 3 (it works with opencv 2). Updated commits in devel branch.

Cool! Thanks for your work!
Do you have a plan that this commit merge to master branch and release new version?

Best regards,
  Nobuhiro

**Comment by cmauri** [comment]
Hi!,

Sorry for the delay.

Yes! Sure! But, could you please confirm that it compiles fine with opencv 3? (Not tested by myself)

Regards,
Cesar

**Comment by cmauri** [comment]
Released version 2.1.1 which fully supports OpenCV 2 and 3 under linux.

**Comment by iwamatsu** [comment]
Cool, thanks.
BTW, if you need to update this version to debian/unstable, let me know.
I am DD, I can upload your package .
  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841407
