### ISSUE TITLE
Unable to change camera

### ISSUE THREAD

**Issue by ckdarby** [cmauri/eviacam#23]
Initial set up I selected the wrong camera but now I'm unable to get back to the original set up that allows me to select the camera options.

When trying to change in the general options I'm given this when clicking "Change":
![Selection_088](https://user-images.githubusercontent.com/220283/71768795-af348800-2ee7-11ea-931e-b15ff0cf2e5a.png)

**Comment by cmauri** [comment]
The "Change" button should do the job. After restarting the app it should ask again to choose the camera (of more than one available). 

If this does not work, you could try going to the registry editor (regedit), removing the following key and then restarting eViacam

HKEY_CURRENT_USER/Software/eviacam/settings/cameraName

**Comment by ckdarby** [comment]
I had to use the application menu to exit for it to reprompt.

I was also able to bypass this with the CLI by passing -c with a one off value.

Sadly it doesn't work with my normal camera, only the IR camera :(
