### ISSUE TITLE
Change language -> "locale 'en_GB' cannot be set."

### ISSUE THREAD

**Issue by chb9** [cmauri/eviacam#7]
If I change the language of eViacam via settings for example to "English" and restart eViacam the error message

> locale 'en_GB' cannot be set.

appears. (See attached Screenshot) 
![locale_error](https://user-images.githubusercontent.com/30769158/29002693-8ef21774-7aa8-11e7-9f7d-1a6a3a790493.png)

eViacam starts in the changed language but this error appears on every start until I changed the language back to "system default".

Happened with Debian 9, eViacam installed via Debian repository and also with the latest master branch.

**Comment by cmauri** [comment]
Do you have the locale 'en_GB' installed on your system?

**Comment by chb9** [comment]
Thank you, now the error message is gone.

I added "en_GB.utf8" in "/etc/locale.gen" and run "sudo locale-gen".
